cancel_on_object = "{} 的 {} 功能並未開啟！取消下載 {} 檔案。"
wrong_with_object = "下載 {} 時遇到問題！取消下載 {} 的 {} 檔案"
wrong_with_downloading_url = "下載 {} 時遇到問題！網址為 {}"
wrong_with_alert = '你可以按任意鍵以繼續下載其他檔案，或是 Ctrl+C 中斷程式運行'
course_download_info = '現在正在下載 {} ...'
course_module_download_info = '現在正在下載 {} 的 {} ...'
course_finish_info = '{} 下載完畢！'
crawler_download_info = '下載 {}...'
crawler_download_fail = '下載 {} 時發生問題！（網址：{}）'
object_download_info = '現在正在下載 {} 的 {} ...'
object_finish_info = '{} 的 {} 下載完畢！'
crawler_timeour_error = '下載遭到 Ceiba 伺服器阻止，沉睡 5 秒鐘後重試...'
skip_external_href = '外部連結 {}，取消下載'
http_not_found_error = '[404 not found] 下載 {} 時發生問題！（網址：{}）'
error_skip_and_continue_download = '下載 {} 的 {} 時發生問題！繼續下載其他部分...'
